### ISSUE TITLE
mysql 8 connector

### ISSUE THREAD

**Issue by axlroden** [alvistack/ansible-role-bitbucket#2]
Would be awesome if you could add option for mysql 8 jdbc connector as well.
https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-8.0.21.tar.gz

**Comment by hswong3i** [comment]
You better don't do that, Atlassian only support MySQL JDBC 5.x right now. I tried before with 8.x and got error :-(

**Comment by axlroden** [comment]
Works fine for me ? Some previous versions did not support it yet.

**Comment by hswong3i** [comment]
See https://confluence.atlassian.com/bitbucketserver050/connecting-bitbucket-server-to-mysql-913475061.html

> JDBC driver support
> Please be aware that version 8.0.11 of MySQL JDBC driver is not supported.

**Comment by axlroden** [comment]
Sorry you are right for bitbucket, i just found the same as you, I just converted confluence successfully from mysql 5 to 8, but does not look like bitbucket will work. 
Maybe I should just do postgresql :/

**Comment by hswong3i** [comment]
My comment for Atlassian:
- Only use OpenJDK 11, when ALL its product family members are ready (yes, I means including [Bamboo](https://jira.atlassian.com/browse/BAM-20031))
- Only use PostgreSQL if possible (because Atlassian primarily using it daily and internally), no thanks for MySQL (due to their buggy implementation on utf8mb4 connection years before, my client got a broken JIRA database due to a 😀)

**Comment by axlroden** [comment]
I hear you, getting frustrating to upgrade..
